name: Publish Site

on:
  push:
    branches: [ master ]

jobs:
  hugo-build:
    name: Hugo Build
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm

      - run: make deps

      - run: make build

      - name: Archive site
        uses: actions/upload-artifact@v2
        with:
          name: site
          path: public/
          retention-days: 1

  hugo-deploy:
    name: Hugo Deploy
    needs: hugo-build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Download site archive
        uses: actions/download-artifact@v2
        with:
          name: site
          path: public/

      - name: Deploy to S3
        run: |
          aws s3 sync --delete ./public s3://$AWS_S3_BUCKET
          aws cloudfront create-invalidation --distribution-id E2JSC1AZT8OHDX --paths "/*"
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}